{{- $gatewayName := default "traefik" $.Values.networking.gatewayName -}}
{{- $gatewayNamespace := default "ingress-traefik" $.Values.networking.gatewayNamespace -}}
{{- $ingressHosts := $.Values.networking.ingressHosts | default dict }}
{{- $lapisHost := $ingressHosts.lapis | default (include "loculus.ingressHost" (include "loculus.lapisUrlTemplate" .)) }}
{{- $traefikApiVersion := ternary "traefik.io/v1alpha1" "traefik.containo.us/v1alpha1" (eq (int $.Values.networking.traefikVersion) 3) -}}
{{- $enabledOrganismsResult := (include "loculus.enabledOrganisms" . | fromJson) }}
{{- $enabledOrganismsList := $enabledOrganismsResult.organisms }}
{{- $organismKeys := list -}}
{{- range $_, $item := $enabledOrganismsList -}}
  {{- $organismKeys = append $organismKeys $item.key -}}
{{- end -}}
apiVersion: {{ $traefikApiVersion }}
kind: Middleware
metadata:
  name: cors-all-origins
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "POST"
      - "HEAD"
    accessControlAllowOriginList:
      - "*"
    accessControlMaxAge: 100
    accessControlAllowHeaders:
      - "*"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lapis-ingress
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gatewayName }}
      namespace: {{ $gatewayNamespace }}
      sectionName: websecure
  hostnames:
    - {{ if eq $.Values.environment "server" }}{{ $lapisHost }}{{ end }}
  rules:
    {{- range $key := $organismKeys }}
    - matches:
        - path:
            type: PathPrefix
            value: /{{ $key }}/
      filters:
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: cors-all-origins
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: strip-{{ $key }}-prefix
      backendRefs:
        - group: ""
          kind: Service
          name: {{ template "loculus.lapisServiceName" $key }}
          port: 8080
          weight: 1
    {{- end }}
  {{- if eq $.Values.environment "server" }}
  {{- end }}

{{- range $key := $organismKeys }}
---
apiVersion: {{ $traefikApiVersion }}
kind: Middleware
metadata:
  name: strip-{{ $key }}-prefix
spec:
  stripPrefix:
    prefixes:
      - /{{ $key }}/
{{- end }}
---
apiVersion: {{ $traefikApiVersion }}
kind: Middleware
metadata:
  name: redirect-slash
spec:
  redirectRegex:
    regex: ".*"
    replacement: "$0/"
    permanent: true
---
# This route is only used to redirect from $LAPIS_URL/$ORGANISM_NAME to $LAPIS_URL/$ORGANISM_NAME/
# We need to do this so we can strip the /$ORGANISM_NAME/ prefix in the main lapis route.
{{- $redirectMiddlewareList := list -}}
{{- if $.Values.networking.enforceHTTPS -}}
  {{- $redirectMiddlewareList = append $redirectMiddlewareList "redirect-middleware" }}
{{- end }}
{{- $redirectMiddlewareList = append $redirectMiddlewareList "redirect-slash" }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: lapis-redirect-ingress
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ $gatewayName }}
      namespace: {{ $gatewayNamespace }}
      sectionName: websecure
  hostnames:
    - {{ if eq $.Values.environment "server" }}{{ $lapisHost }}{{ end }}
  rules:
    {{- range $key := $organismKeys }}
    - matches:
        - path:
            type: Exact
            value: /{{ $key }}
      filters:
        {{- range $middlewareName := $redirectMiddlewareList }}
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: {{ $middlewareName }}
        {{- end }}
      backendRefs:
        - group: ""
          kind: Service
          name: {{ template "loculus.lapisServiceName" (first $organismKeys) }}
          port: 8080
          weight: 1
    {{- end }}
